# Generated by Django 4.0.5 on 2023-06-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_win',
            field=models.BooleanField(default=False),
        ),
    ]
