# Generated by Django 4.0.5 on 2023-06-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_is_win'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_win',
            new_name='active_game',
        ),
    ]
