# Generated by Django 4.0.5 on 2023-06-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_is_win_game_active_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.CharField(default='         ', max_length=9),
        ),
    ]
