# Generated by Django 4.0.5 on 2023-06-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_current_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_players',
            field=models.IntegerField(default=1),
        ),
    ]
