# Generated by Django 4.0.5 on 2023-06-13 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_current_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='active_game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='current_players',
        ),
    ]
