# Generated by Django 4.0.5 on 2023-06-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_game_active_game_remove_game_current_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
